# Generated by Django 6.0.6 on 2026-06-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_payment_checkout_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
