# Generated by Django 6.0.6 on 2026-06-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_payment_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
